from datetime import UTC, datetime, timedelta

import httpx
from fastapi import HTTPException, status

from app.core.config import settings

_GOOGLE_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"


async def exchange_google_token(
    code: str,
    code_verifier: str,
    redirect_uri: str,
) -> dict:
    """Exchange a Google authorization code for OAuth tokens server-side.

    Args:
        code: Authorization code from the Google OAuth callback.
        code_verifier: PKCE verifier generated by the frontend.
        redirect_uri: Must match the URI used in the authorization request.

    Returns:
        Dict with access_token, refresh_token, expires_at keys.

    Raises:
        HTTPException: 503 if client_secret is not configured.
        HTTPException: 400 if Google rejects the token exchange.
        HTTPException: 502 if Google returns an incomplete token response.
    """
    if not settings.google_calendar_client_secret:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Google Calendar client secret ist nicht konfiguriert.",
        )

    async with httpx.AsyncClient() as client:
        response = await client.post(
            _GOOGLE_TOKEN_ENDPOINT,
            data={
                "client_id": settings.google_calendar_client_id,
                "client_secret": settings.google_calendar_client_secret,
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": redirect_uri,
                "code_verifier": code_verifier,
            },
        )

    body = response.json()
    if response.status_code != 200:
        error = (
            body.get("error_description")
            or body.get("error")
            or "Token-Austausch fehlgeschlagen."
        )
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Google Token-Austausch fehlgeschlagen: {error}",
        )

    access_token = body.get("access_token")
    refresh_token = body.get("refresh_token")
    expires_in = body.get("expires_in")

    if not access_token or not refresh_token or expires_in is None:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Google hat keine vollständigen Tokens zurückgegeben.",
        )

    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "expires_at": datetime.now(tz=UTC) + timedelta(seconds=int(expires_in)),
    }
